export const states = {
  al: { name: "Alabama", code: "01"},
  ak: { name: "Alaska", code: "02"},
  az: { name: "Arizona", code: "04"},
  ar: { name: "Arkansas", code: "05"},
  ca: { name: "California", code: "06"},
  co: { name: "Colorado", code: "08"},
  cn: { name: "Connecticut", code: "09"},
  dc: { name: "District of Columbia", code: "11"},
  de: { name: "Delaware", code: "10"},
  fl: { name: "Florida", code: "12"},
  ga: { name: "Georgia", code: "13"},
  hi: { name: "Hawaii", code: "15"},
  id: { name: "Idaho", code: "16"},
  il: { name: "Illinois", code: "17"},
  in: { name: "Indiana", code: "18"},
  io: { name: "Iowa", code: "19"},
  ka: { name: "Kansas", code: "20"},
  ke: { name: "Kentucky", code: "21"},
  lo: { name: "Louisiana", code: "22"},
  me: { name: "Maine", code: "23"},
  ma: { name: "Massachusetts", code: "25"},
  md: { name: "Maryland", code: "24"},
  mi: { name: "Michigan", code: "26"},
  mn: { name: "Minnesota", code: "27"},
  ms: { name: "Mississippi", code: "28"},
  mo: { name: "Missouri", code: "29"},
  mt: { name: "Montana", code: "30"},
  ne: { name: "Nebraska", code: "31"},
  nh: { name: "New Hampshire", code: "33"},
  nv: { name: "Nevada", code: "32"},
  nj: { name: "New Jersey", code: "34"},
  nm: { name: "New Mexico", code: "35"},
  ny: { name: "New York", code: "36"},
  nc: { name: "North Carolina", code: "37"},
  nd: { name: "North Dakota", code: "38"},
  oh: { name: "Ohio", code: "39"},
  ok: { name: "Oklahoma", code: "40"},
  or: { name: "Oregon", code: "41"},
  pe: { name: "Pennsylvania", code: "42"},
  ri: { name: "Rhode Island", code: "44"},
  sc: { name: "South Carolina", code: "45"},
  sd: { name: "South Dakota", code: "46"},
  te: { name: "Tennessee", code: "47"},
  tx: { name: "Texas", code: "48"},
  ut: { name: "Utah", code: "49"},
  vt: { name: "Vermont", code: "50"},
  va: { name: "Virginia", code: "51"},
  wv: { name: "West Virginia", code: "54"},
  wa: { name: "Washington", code: "53"},
  wy: { name: "Wyoming", code: "56"},
  wi: { name: "Wisconsin", code: "55"},
  pr: { name: "Puerto Rico", code: "72"}
}